now we check the ngx_devel_kit dependency at config time and provide a more friendly error message if it is missing.

diff --git a/config b/config
--- a/config
+++ b/config
@@ -1,3 +1,10 @@
+if echo $HTTP_MODULES | grep " ndk_http_module" > /dev/null; then
+    echo "found ngx_devel_kit for ngx_form_input; looks good."
+else
+    echo "error: ngx_devel_kit is required to build ngx_form_input; please put it before ngx_form_input." 1>&2
+    exit 1
+fi
+
 ngx_addon_name=ngx_http_form_input_module
 HTTP_AUX_FILTER_MODULES="$HTTP_AUX_FILTER_MODULES ngx_http_form_input_module"
 NGX_ADDON_SRCS="$NGX_ADDON_SRCS $ngx_addon_dir/src/ngx_http_form_input_module.c"
